steps:
- name: gcr.io/kaniko-project/executor
  args:
  - --destination=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  - --cache=true

- name: 'gcr.io/cloud-builders/docker'
  args: 
  - pull
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA

- name: 'gcr.io/gcp-runtimes/container-structure-test'
  args: 
  - test 
  - --image
  - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
  - --config
  - container-structure-test.yml

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
  - BRANCH_NAME=$BRANCH_NAME
  - PROJECT_ID=$PROJECT_ID
  - REPO_NAME=$REPO_NAME
  - COMMIT_SHA=$COMMIT_SHA
  - _DOCKERHUB_PASSWORD=$_DOCKERHUB_PASSWORD
  args:
  - ./scripts/push_dockerhub.sh 
